### ISSUE TITLE
Recreating 754df5bbf2a9_testdriven-app_users_1 ... error  

### ISSUE THREAD

**Issue by gimmy1** [testdrivenio/testdriven-app-2.3#18]
ERROR: for 754df5bbf2a9_testdriven-app_users_1  Cannot start service users: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": permission denied": unknown  ERROR: for users  Cannot start service users: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": permission denied": unknown

**Comment by mjhea0** [comment]
Addressed via email
