### ISSUE TITLE
python test scripts doesn't actually fail

### ISSUE THREAD

**Issue by kjuulh** [testdrivenio/testdriven-app-2.3#24]
```python
@cli.command()
def test():
    """Runs the tests without code coverage"""
    tests = unittest.TestLoader().discover("project/tests", pattern="test*.py")
    result = unittest.TextTestRunner(verbosity=2).run(tests)
    if result.wasSuccessful():
        return 0
    return 1
```

I've tried creating a few of my own services and noticed that the tests didn't actually fail the test.sh script.
I found out that we need a concrete error for this to register to the inspect $? users etc.

I recommend changing the return 1 to sys.exit(result) instead, or another message.

I haven't tested it in the test-ci.sh, but I guess it might be the same. I also recall that @mjhea0 mentioned it in the book, but here is a solution that works for me at least.

```python
if result.wasSuccessful():
    return 0
sys.exit(result)
```

#edit forgot changed code

**Comment by mjhea0** [comment]
👍 

I'll include this in the next update to the course. Cheers!
