### ISSUE TITLE
cypress failed to load /

### ISSUE THREAD

**Issue by Stegnerd** [testdrivenio/testdriven-app-2.3#25]
In the beginning of CH 4, the first test has you run cy.visit('/') which returns a 404 for me. If I change that to cy.visit('http://localhost/') the test passes. From my understanding this will fail travis or any other env. I was curious as to how yours worked without the local host part?

here is the error I receive

CypressError: cy.visit() failed trying to load:

/

We failed looking for this file at the path:

/redacted/testdriven-app/

The internal Cypress web server responded with:

  > 404: Not Found

Thank you

**Comment by mjhea0** [comment]
Are you setting the `baseURL` in *cypress.json*?

```json
{
  "baseUrl": "http://localhost",
  "video": false
}
```

https://github.com/testdrivenio/testdriven-app-2.4/blob/part4/cypress.json

**Comment by Stegnerd** [comment]
ultimately I saw that in the source code but on page 227 the only thing added was 
{
  "video": false
}

Maybe that is just a discrepancy in the text, but learning cypress for the first time this confused me slightly. Maybe it could be included in future revisions. BTW  love the text otherwise! Great job!

**Comment by mjhea0** [comment]
I did release a new version. Did you not get the email about it? Want to shoot me a quick email? michael at mherman dot org
